# Generated by Django 6.0 on 2025-12-12 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=15, verbose_name='Kürzel')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Stufe',
            fields=[
                ('stufe', models.IntegerField(primary_key=True, serialize=False, verbose_name='Stufe')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Stufe',
                'verbose_name_plural': 'Stufen',
            },
        ),
        migrations.CreateModel(
            name='Karteikarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField(verbose_name='Frage')),
                ('antwort', models.TextField(verbose_name='Antwort')),
                ('erstelldatum', models.DateField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aenderungsdatum', models.DateField(auto_now=True, verbose_name='Geändert am')),
                ('ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ersteller')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lernen.kategorie', verbose_name='Kategorie')),
                ('stufe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='lernen.stufe', verbose_name='Stufe')),
            ],
            options={
                'verbose_name': 'Karteikarte',
                'verbose_name_plural': 'Karteikarten',
            },
        ),
        migrations.CreateModel(
            name='UserKK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Anzahl Versuche')),
                ('lerndatum', models.DateField(auto_now=True, verbose_name='Geübt am')),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('karteikarte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lernen.karteikarte', verbose_name='Karteikarte')),
            ],
            options={
                'verbose_name': 'User - Karteikarte',
                'verbose_name_plural': 'User - Karteikarten',
            },
        ),
    ]
