# Generated by Django 6.0 on 2025-12-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkk',
            name='gewusst',
            field=models.BooleanField(default=False, verbose_name='Antwort gewusst'),
        ),
    ]
